In [69]:
import numpy as np   
import random

class McCullochPitts(object):
  """Implements a perceptron network"""
  def __init__(self, input_size,lr=1, epochs=1000):
    self.W = np.zeros(input_size+1)
    # add one for bias
    self.epochs = epochs
    self.lr =lr
  def activation_fn(self, z, bk):
    #return (x >= 0).astype(np.float32)
    return 1 if z >= -bk else 0
 
  def predict(self, x, bk):
    z = self.W.T.dot(x)
    a = self.activation_fn(z, bk)
    return a
  def fit(self, X, Y):
    bk = 0
    e = 0
    for _ in range(self.epochs):
      for i in range(Y.shape[0]):
        x = np.insert(X[i], 0, 1,)
        bk += self.lr * e 
        y = self.predict(x, bk)
        e = Y[i] - y
        self.W = self.W + self.lr * e * x


In [43]:
# AND GATE with 2 inputs
if __name__ == '__main__':
    X = np.array([
        [0, 0],
        [0, 1],
        [1, 0],
        [1, 1]
    ])
    Y = np.array([0, 0, 0, 1])
 
    perceptron = McCullochPitts(input_size=2)
    perceptron.fit(X, Y)
    print(X)
    print(perceptron)

[[0 0]
 [0 1]
 [1 0]
 [1 1]]


In [4]:
# AND GATE with 5 inputs
if __name__ == '__main__':
  X = np.array([
        [0,0,0,0,0],
        [0,0,0,0,1],
        [0,0,0,1,0],
        [0,0,0,1,1],
        [0,0,1,0,0],
        [0,0,1,0,1],
        [0,0,1,1,0],
        [0,0,1,1,1],
        [0,1,0,0,0],
        [0,1,0,0,1],
        [0,1,0,1,0],
        [0,1,0,1,1],
        [0,1,1,0,0],
        [0,1,1,0,1],
        [0,1,1,1,0],
        [0,1,1,1,1],
        [1,0,0,0,0],
        [1,0,0,0,1],
        [1,0,0,1,0],
        [1,0,0,1,1],
        [1,0,1,0,0],
        [1,0,1,0,1],
        [1,0,1,1,0],
        [1,0,1,1,1],
        [1,1,0,0,0],
        [1,1,0,0,1],
        [1,1,0,1,0],
        [1,1,0,1,1],
        [1,1,1,0,0],
        [1,1,1,0,1],
        [1,1,1,1,0],
        [1,1,1,1,1]
    ])
  Y = np.array([0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1])
 
  perceptron = McCullochPitts(input_size=5)
  perceptron.fit(X, Y)
  print(X)
  print(Y)

[[0 0 0 0 0]
 [0 0 0 0 1]
 [0 0 0 1 0]
 [0 0 0 1 1]
 [0 0 1 0 0]
 [0 0 1 0 1]
 [0 0 1 1 0]
 [0 0 1 1 1]
 [0 1 0 0 0]
 [0 1 0 0 1]
 [0 1 0 1 0]
 [0 1 0 1 1]
 [0 1 1 0 0]
 [0 1 1 0 1]
 [0 1 1 1 0]
 [0 1 1 1 1]
 [1 0 0 0 0]
 [1 0 0 0 1]
 [1 0 0 1 0]
 [1 0 0 1 1]
 [1 0 1 0 0]
 [1 0 1 0 1]
 [1 0 1 1 0]
 [1 0 1 1 1]
 [1 1 0 0 0]
 [1 1 0 0 1]
 [1 1 0 1 0]
 [1 1 0 1 1]
 [1 1 1 0 0]
 [1 1 1 0 1]
 [1 1 1 1 0]
 [1 1 1 1 1]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]


In [5]:
# OR GATE with 5 inputs
if __name__ == '__main__':
  X = np.array([
        [0,0,0,0,0],
        [0,0,0,0,1],
        [0,0,0,1,0],
        [0,0,0,1,1],
        [0,0,1,0,0],
        [0,0,1,0,1],
        [0,0,1,1,0],
        [0,0,1,1,1],
        [0,1,0,0,0],
        [0,1,0,0,1],
        [0,1,0,1,0],
        [0,1,0,1,1],
        [0,1,1,0,0],
        [0,1,1,0,1],
        [0,1,1,1,0],
        [0,1,1,1,1],
        [1,0,0,0,0],
        [1,0,0,0,1],
        [1,0,0,1,0],
        [1,0,0,1,1],
        [1,0,1,0,0],
        [1,0,1,0,1],
        [1,0,1,1,0],
        [1,0,1,1,1],
        [1,1,0,0,0],
        [1,1,0,0,1],
        [1,1,0,1,0],
        [1,1,0,1,1],
        [1,1,1,0,0],
        [1,1,1,0,1],
        [1,1,1,1,0],
        [1,1,1,1,1]
    ])
  Y = np.array([0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1])
 
  perceptron = McCullochPitts(input_size=5)
  perceptron.fit(X, Y)
  print(X)
  print(perceptron)

[[0 0 0 0 0]
 [0 0 0 0 1]
 [0 0 0 1 0]
 [0 0 0 1 1]
 [0 0 1 0 0]
 [0 0 1 0 1]
 [0 0 1 1 0]
 [0 0 1 1 1]
 [0 1 0 0 0]
 [0 1 0 0 1]
 [0 1 0 1 0]
 [0 1 0 1 1]
 [0 1 1 0 0]
 [0 1 1 0 1]
 [0 1 1 1 0]
 [0 1 1 1 1]
 [1 0 0 0 0]
 [1 0 0 0 1]
 [1 0 0 1 0]
 [1 0 0 1 1]
 [1 0 1 0 0]
 [1 0 1 0 1]
 [1 0 1 1 0]
 [1 0 1 1 1]
 [1 1 0 0 0]
 [1 1 0 0 1]
 [1 1 0 1 0]
 [1 1 0 1 1]
 [1 1 1 0 0]
 [1 1 1 0 1]
 [1 1 1 1 0]
 [1 1 1 1 1]]
[0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


In [6]:
# OR GATE with 2 inputs
if __name__ == '__main__':
  X = np.array([
        [0, 0],
        [0, 1],
        [1, 0],
        [1, 1]
    ])
  Y = np.array([0, 1, 1, 1])
 
  perceptron = McCullochPitts(input_size=2)
  perceptron.fit(X, Y)
  print(X)
  print(Y)


[[0 0]
 [0 1]
 [1 0]
 [1 1]]
[0 1 1 1]


In [ ]:
# Second Attempt

In [ ]:
def initialize_weights():
    # Generate random numbers
    random.seed(1)

    # Assign random weights to a 4 x 1 matrix
    synaptic_weights = np.array([[0],[0],[0],[0]])
    synaptic_weights = synaptic_weights.astype('int')
    return synaptic_weights

def learn(inputs, synaptic_weights, bias):
    return np.dot(inputs.T, synaptic_weights) + bias

def train(inputs, expected_output, synaptic_weights, bias, learning_rate, training_iterations):
      for epoch in range(training_iterations):
            # Forward pass -- Pass the training set through the network.
          predicted_output = learn(inputs, synaptic_weights, bias)

          # Backaward pass
          # Calculate the error
          error = (expected_output - predicted_output)

          # Adjust the weights and bias by a factor
          weight_factor = np.dot(inputs.T, error.T) * learning_rate
          bias_factor = error * learning_rate

          # Update the synaptic weights
          synaptic_weights += weight_factor.astype('int')

          # Update the bias
          bias += bias_factor

          if ((epoch % 1000) == 0):
              print("Epoch", epoch)
              print("Predicted Output = ", predicted_output.T)
              print("Expected Output = ", expected_output.T)
              print()
      return synaptic_weights

In [ ]:
synaptic_weights = initialize_weights()

    # The training set
inputs = np.array([[0, 1],
                    [1, 0],
                    [1, 0],
                    [1,1]])

    # Target set
expected_output = np.array([0, 0,0, 1])

    # Test set
test = np.array([1, 0,0, 1])
print(inputs)
print(synaptic_weights)
    # Train the neural network
trained_weights = train(inputs, expected_output, synaptic_weights, bias=0.001, learning_rate=0.98,
                            training_iterations=100)